version: '3.3'

services:
  db:
    image: postgres:13.3-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  api:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev

volumes:
  postgres: {}
