name: Bump the Version Number And Run Pre Deploy Checks

on:
  push:
    branches:
      - develop
      - qa
      - main

defaults:
  run:
    shell: bash

jobs:
  update-version:
    name: Update package.json Version
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Change Version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            npm version minor --no-git-tag-version
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            npm version patch --no-git-tag-version
          else
            npm version major --no-git-tag-version
          fi

      - name: Get current package version
        id: pkg
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: 'package.json'
          message: '[RELEASE] v${{ steps.pkg.outputs.current-version}}'
          tag: 'v${{ steps.pkg.outputs.current-version}} --force'
